version: '3'
services:

  #PHP & APACHE
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: api_logistik
    depends_on:
      - database
    volumes:
      - .:/var/www/html

    ports:
      - "8080:80"
    networks:
      - internal

  #MySQL Service
  database:
    image: mysql:5.7
    container_name: database_logistik
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - vol_mysql_data:/var/lib/mysql/
    networks:
      - internal

#Docker Networks
networks:
  internal:
    driver: bridge

#Volumes
volumes:
  vol_mysql_data:
    driver: local

  vendor_data:
    driver: local
