version: '3'
services:

  #PHP & APACHE
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-logistik-production
    volumes:
      - vendor_data:/var/www/html/vendor
      - .env.production:/var/www/html/.env
    ports:
      - "8080:80"
    networks:
      - internal
    logging:
        driver: "awslogs"
        options:
           awslogs-region: "ap-southeast-1"
           awslogs-group: "pikobar-logistik"
           awslogs-stream: "backend-production"
    
#Docker Networks
networks:
  internal:
    external:
       name: gateway

#Volumes 
volumes:
  vendor_data:
    driver: local
