apiVersion: v1
kind: Secret
metadata:
  name: logistik-secret-file-prod
  namespace: pikobar-logistik
data:
  DB_PASSWORD: "%DB_PASSWORD%"

  JWT_SECRET: "%JWT_SECRET%"

  PELAPORAN_AUTH_PASSWORD: "%PELAPORAN_AUTH_PASSWORD%"

  MAIL_PASSWORD: "%MAIL_PASSWORD%"

  WMS_JABAR_API_KEY: "%WMS_JABAR_API_KEY%"

  DASHBOARD_PIKOBAR_API_KEY: "%DASHBOARD_PIKOBAR_API_KEY%"